In [1]:
import numpy as np

In [7]:
# 1-мерный массив формой (длиной) 5 элементов
# со случайными значениями из равномерного распределения
# распредления от 0 до 1
arr_1 = np.random.random(5)
arr_1

array([0.12194193, 0.84441857, 0.23399913, 0.80118214, 0.31403161])

In [8]:
arr_1.dtype

dtype('float64')

In [9]:
arr_1.astype("float16")

array([0.12195, 0.844  , 0.234  , 0.8013 , 0.314  ], dtype=float16)

In [11]:
# 2- vfccbd
np.random.random((3,5))

array([[0.07603472, 0.01321563, 0.99803583, 0.27457065, 0.92580365],
       [0.78866577, 0.24506772, 0.72308909, 0.97437487, 0.59093005],
       [0.85940121, 0.49424282, 0.56073041, 0.27000917, 0.273582  ]])

In [15]:
# генерация массива с случайными целочисленными значениями
# если без формы, то это будет одно значение (скаляр)
# np.random.randint(0,10)
np.random.randint(10)

0

In [17]:
# 1- мерный массив со случ целыми числами
np.random.randint(-10, 10, size=10)

array([ 9, -4, -9,  5, -7,  1,  8,  2, -5, -1])

In [19]:
# 2-мерный массив со случ целыми значениями
np.random.randint(10, 100, size=(3,5))

array([[44, 46, 29, 41, 90],
       [16, 83, 54, 26, 41],
       [76, 65, 34, 71, 96]])

In [20]:
# 3-мерный массив (тензор 3 ранга) со случ целыми значениями
np.random.randint(10, 100, size=(3,5,4))

array([[[28, 97, 44, 39],
        [25, 98, 41, 84],
        [43, 64, 31, 72],
        [33, 98, 84, 30],
        [58, 81, 45, 37]],

       [[50, 11, 30, 39],
        [97, 37, 67, 75],
        [12, 48, 90, 12],
        [49, 33, 29, 67],
        [17, 20, 91, 14]],

       [[59, 40, 14, 66],
        [47, 67, 61, 72],
        [29, 88, 97, 50],
        [75, 57, 14, 40],
        [93, 11, 78, 86]]])

In [22]:
# 1-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# медиана  = 0, стандартное отклонение  = 1
np.random.randn(15)

array([ 0.95745492,  1.66210751,  1.71109201,  0.72132472, -1.26725198,
        0.78304098,  0.60921242,  0.2346552 , -1.42666391, -1.12219955,
        1.02278818, -1.36315001, -0.79383578,  1.59593075,  1.02308906])

In [23]:
# 2-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# медиана  = 0, стандартное отклонение  = 1
np.random.randn(5,3)

array([[ 0.59683861,  0.88646314, -0.90593826],
       [ 0.19008248,  0.58966967, -0.28099076],
       [ 1.38697212, -0.77581666,  3.43117031],
       [ 2.43470858, -0.82489023,  0.2529482 ],
       [ 0.23905168, -0.23131594,  0.8681453 ]])

In [24]:
# 2-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# медиана  = 1, стандартное отклонение  = 2
np.random.normal(1,2, (3,3))

array([[ 0.0131313 ,  0.58769731, -3.52687496],
       [-2.71057299,  1.88572296,  1.71897489],
       [ 0.35946762,  3.72485639,  2.99132549]])

- атрибуты

In [25]:
arr_2 =np.random.randint(10, size =(3,5))
arr_2

array([[7, 7, 9, 6, 6],
       [5, 6, 4, 6, 9],
       [4, 5, 6, 8, 4]])

In [26]:
# форма
arr_2.shape

(3, 5)

In [27]:
# общее количество значений
arr_2.size

15

In [28]:
# мерность массива (количество измерений/ осей)
arr_2.ndim

2

In [29]:
# занимаемый обьем памяти
arr_2.nbytes

60

In [30]:
# тип данных
arr_2.dtype

dtype('int32')

- Методы

In [34]:
arr_2= np.random.randint(10, size=(3,5))
arr_2

array([[7, 8, 2, 1, 4],
       [9, 5, 3, 1, 0],
       [4, 6, 5, 0, 7]])

In [35]:
# сортировка по столбцам
arr_2.sort(axis=0)

In [36]:
arr_2

array([[4, 5, 2, 0, 0],
       [7, 6, 3, 1, 4],
       [9, 8, 5, 1, 7]])

In [37]:
# сортировка по строкам
arr_2.sort(axis=1)

In [38]:
arr_2

array([[0, 0, 2, 4, 5],
       [1, 3, 4, 6, 7],
       [1, 5, 7, 8, 9]])

In [40]:
# реверс (переворот) соритированных значений по строкам
arr_2.sort(axis=1)
arr_2[:, ::-1]


array([[5, 4, 2, 0, 0],
       [7, 6, 4, 3, 1],
       [9, 8, 7, 5, 1]])

In [41]:
# возвращает в одномерный массив
arr_2.flatten()

array([0, 0, 2, 4, 5, 1, 3, 4, 6, 7, 1, 5, 7, 8, 9])

In [42]:
arr_2.min(), arr_2.max(), arr_2.mean()

(0, 9, 4.133333333333334)

- Индексация


In [43]:
arr_2

array([[0, 0, 2, 4, 5],
       [1, 3, 4, 6, 7],
       [1, 5, 7, 8, 9]])

In [45]:
# прямая индексация 
arr_2[1]

array([1, 3, 4, 6, 7])

In [46]:
# обратная индексация 
arr_2[-1]

array([1, 5, 7, 8, 9])

In [47]:
# извлечение значений элементов массива
# стандартный питонячий синтаксис
arr_2[1][-1]

7

In [48]:
# синтаксис numpy
arr_2[1,-1]

7

- Срезы


In [49]:
arr_2

array([[0, 0, 2, 4, 5],
       [1, 3, 4, 6, 7],
       [1, 5, 7, 8, 9]])

In [51]:
arr_2[:2]

array([[0, 0, 2, 4, 5],
       [1, 3, 4, 6, 7]])

In [52]:
arr_2[:,:2]

array([[0, 0],
       [1, 3],
       [1, 5]])

In [53]:
arr_2[:,1:4]

array([[0, 2, 4],
       [3, 4, 6],
       [5, 7, 8]])

In [54]:
arr_2[1:, 1:4]

array([[3, 4, 6],
       [5, 7, 8]])