#  Анализ данных из Росстат

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [4]:
# загрузка данных 
raw_df = pd.read_excel("data/cen-god.xls", skiprows=2)
raw_df.head(10)

ПОКАЗАТЕЛИ    1991    1992     1993  \
0  Средние потребительские цены на отдельные виды...    NaN     NaN      NaN   
1                  Говядина (кроме бескостного мяса)  15.54   221.5  2201.27   
2                   Свинина (кроме бескостного мяса)  14.38     260  2672.81   
3                     Куры охлажденные и мороженые1)  13.57  194.76  2238.98   
4                                  Колбаса вареная2)     17     271   3351.3   
5                           Консервы мясные3), 350 г   8.87   163.9  1165.48   
6                     Рыба мороженая неразделанная4)   2.32   129.5  1088.73   
7              Рыба соленая, маринованная, копченая    5.72   272.6  2598.96   
8  Консервы рыбные натуральные и с добавлением ма...   3.91     120  1040.71   
9                                Масло сливочное 5)   12.24     413  2912.58   

       1994   1995   1996   1997   1998   1999  ...    2012    2013    2014  \
0       NaN    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN     NaN   
1   5186.28  12547  14137  15787  30.04  42.01  ...  248.47  244.55  272.28   
2   6579.38  15053  16810  19055  33.99  43.37  ...  220.09  214.18  272.36   
3   5677.09  11587  13815  16061  30.74  39.28  ...  117.26  107.03  136.14   
4    8984.1  20016  22859  26767  43.81  61.56  ...  288.23  302.94  310.54   
5   2991.46   6692   7375   7811   15.5  18.16  ...   75.22   79.33   94.42   
6   3675.17   8325   9398   9912  18.93  23.83  ...   85.67   90.79  110.65   
7   7495.95  17488  19912  21402  32.13  47.89  ...  247.61  252.52  292.21   
8   3211.18   8050   8540   8468  13.85  19.96  ...   57.76   60.50   70.12   
9  12984.99  20075  22968  23238  64.44  66.83  ...  260.84  308.92  357.54   

     2015    2016    2017    2018    2019    2020    2021  
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN  
1  314.94  315.02  320.34  330.58  350.05  361.04  416.46  
2  271.08  264.32  255.87  275.26  264.55  269.14  311.84  
3  133.73  138.49  126.29  151.27  143.13  145.55  183.54  
4  344.81  351.27  360.88  382.98  399.37  406.84  450.57  
5  117.04  121.37  125.21  130.13  139.47   153.5  167.04  
6  138.16  147.68  153.03  152.14  170.13  181.08  192.61  
7  352.58  382.54  388.83  398.24  424.54  453.54  525.66  
8   91.94  103.94  109.09  113.71  119.69  135.03  156.01  
9  397.75  477.13  528.83  553.02  613.39  638.69  719.21  

[10 rows x 32 columns]

In [5]:
raw_df.shape # показывает строки столбцы табл

(125, 32)

In [7]:
# очищаем датафрейм от пустых строк  
raw_df = raw_df.dropna()
raw_df.shape

(85, 32)

In [8]:
# Проверка ключей столбцов 
raw_df.columns

Index([' ПОКАЗАТЕЛИ ',           1991,           1992,           1993,
                 1994,           1995,           1996,           1997,
                 1998,           1999,           2000,           2001,
                 2002,           2003,           2004,           2005,
                 2006,           2007,           2008,           2009,
                 2010,           2011,           2012,           2013,
                 2014,           2015,           2016,           2017,
                 2018,           2019,           2020,           2021],
      dtype='object')

In [10]:
raw_df.columns[1:]


Index([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021],
      dtype='object')

In [12]:
type(raw_df.columns[1])

int

In [13]:
# Для удобства приводим значения ключей столбцов в единый строковой тип 
raw_df.columns = raw_df.columns.astype("str")
raw_df.columns

Index([' ПОКАЗАТЕЛИ ', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [14]:
# для того, чтобы категории товаров сиали ключами столбцов  транспонируем таблицу 
raw_df_2 =raw_df.T
raw_df_2

1   \
 ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)   
1991                                      15.54   
1992                                      221.5   
1993                                    2201.27   
1994                                    5186.28   
1995                                      12547   
1996                                      14137   
1997                                      15787   
1998                                      30.04   
1999                                      42.01   
2000                                      52.72   
2001                                      70.33   
2002                                      72.56   
2003                                       73.9   
2004                                      93.41   
2005                                     115.77   
2006                                     131.67   
2007                                     139.49   
2008                                     174.86   
2009                                      185.6   
2010                                     197.64   
2011                                     234.49   
2012                                     248.47   
2013                                     244.55   
2014                                     272.28   
2015                                     314.94   
2016                                     315.02   
2017                                     320.34   
2018                                     330.58   
2019                                     350.05   
2020                                     361.04   
2021                                     416.46   

                                            2   \
 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)   
1991                                     14.38   
1992                                       260   
1993                                   2672.81   
1994                                   6579.38   
1995                                     15053   
1996                                     16810   
1997                                     19055   
1998                                     33.99   
1999                                     43.37   
2000                                     58.45   
2001                                     79.22   
2002                                     80.98   
2003                                     82.42   
2004                                    110.47   
2005                                    131.64   
2006                                       142   
2007                                    149.02   
2008                                    189.42   
2009                                    193.66   
2010                                    198.35   
2011                                    210.89   
2012                                    220.09   
2013                                    214.18   
2014                                    272.36   
2015                                    271.08   
2016                                    264.32   
2017                                    255.87   
2018                                    275.26   
2019                                    264.55   
2020                                    269.14   
2021                                    311.84   

                                          3                  4   \
 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)   
1991                                   13.57                 17   
1992                                  194.76                271   
1993                                 2238.98             3351.3   
1994                                 5677.09             8984.1   
1995                                   11587              20016   
1996                                   13815              22859   
1997                                   16061              26767   
1998                                   30.74              43.81   
1999                                   3

In [15]:
raw_df_2.index

Index([' ПОКАЗАТЕЛИ ', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [16]:
# В качестве ключей столбцов устанавливаем значения  категории "показатели"
raw_df_2.columns = raw_df_2.loc[' ПОКАЗАТЕЛИ ', :]
raw_df_2.head(10)

ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)  \
 ПОКАЗАТЕЛИ   Говядина (кроме бескостного мяса)   
1991                                      15.54   
1992                                      221.5   
1993                                    2201.27   
1994                                    5186.28   
1995                                      12547   
1996                                      14137   
1997                                      15787   
1998                                      30.04   
1999                                      42.01   

 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)  \
 ПОКАЗАТЕЛИ   Свинина (кроме бескостного мяса)   
1991                                     14.38   
1992                                       260   
1993                                   2672.81   
1994                                   6579.38   
1995                                     15053   
1996                                     16810   
1997                                     19055   
1998                                     33.99   
1999                                     43.37   

 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)  \
 ПОКАЗАТЕЛИ   Куры охлажденные и мороженые1)  Колбаса вареная2)   
1991                                   13.57                 17   
1992                                  194.76                271   
1993                                 2238.98             3351.3   
1994                                 5677.09             8984.1   
1995                                   11587              20016   
1996                                   13815              22859   
1997                                   16061              26767   
1998                                   30.74              43.81   
1999                                   39.28              61.56   

 ПОКАЗАТЕЛИ   Консервы мясные3), 350 г  Рыба мороженая неразделанная4)  \
 ПОКАЗАТЕЛИ   Консервы мясные3), 350 г  Рыба мороженая неразделанная4)   
1991                              8.87                            2.32   
1992                             163.9                           129.5   
1993                           1165.48                         1088.73   
1994                           2991.46                         3675.17   
1995                              6692                            8325   
1996                              7375                            9398   
1997                              7811                            9912   
1998                              15.5                           18.93   
1999                             18.16                           23.83   

 ПОКАЗАТЕЛИ   Рыба соленая, маринованная, копченая   \
 ПОКАЗАТЕЛИ   Рыба соленая, маринованная, копченая    
1991                                           5.72   
1992                                          272.6   
1993                                        2598.96   
1994                                        7495.95   
1995                                          17488   
1996                                          19912   
1997                                          21402   
1998                                          32.13   
1999                                          47.89   

 ПОКАЗАТЕЛИ  Консервы рыбные натуральные и с добавлением масла,  350 г  \
 ПОКАЗАТЕЛИ   Консервы рыбные натуральные и с добавлением ма...          
1991                                                       3.91          
1992                                                        120          
1993                                                    1040.71          
1994                                                    3211.18          
1995                                                       8050          
1996                                                       8540          
1997                                                       8468          
1998                                                      13.85

In [17]:
raw_df_2 = raw_df_2.drop(' ПОКАЗАТЕЛИ ')
raw_df_2.head()

ПОКАЗАТЕЛИ  Говядина (кроме бескостного мяса)  \
1991                                     15.54   
1992                                     221.5   
1993                                   2201.27   
1994                                   5186.28   
1995                                     12547   

 ПОКАЗАТЕЛИ  Свинина (кроме бескостного мяса) Куры охлажденные и мороженые1)  \
1991                                    14.38                          13.57   
1992                                      260                         194.76   
1993                                  2672.81                        2238.98   
1994                                  6579.38                        5677.09   
1995                                    15053                          11587   

 ПОКАЗАТЕЛИ  Колбаса вареная2) Консервы мясные3), 350 г  \
1991                        17                     8.87   
1992                       271                    163.9   
1993                    3351.3                  1165.48   
1994                    8984.1                  2991.46   
1995                     20016                     6692   

 ПОКАЗАТЕЛИ  Рыба мороженая неразделанная4)  \
1991                                   2.32   
1992                                  129.5   
1993                                1088.73   
1994                                3675.17   
1995                                   8325   

 ПОКАЗАТЕЛИ  Рыба соленая, маринованная, копченая   \
1991                                          5.72   
1992                                         272.6   
1993                                       2598.96   
1994                                       7495.95   
1995                                         17488   

 ПОКАЗАТЕЛИ  Консервы рыбные натуральные и с добавлением масла,  350 г  \
1991                                                       3.91          
1992                                                        120          
1993                                                    1040.71          
1994                                                    3211.18          
1995                                                       8050          

 ПОКАЗАТЕЛИ  Масло сливочное 5)  Масло подсолнечное 6)   ...  \
1991                       12.24                   5.48  ...   
1992                         413                    190  ...   
1993                     2912.58                 1364.9  ...   
1994                    12984.99                5306.54  ...   
1995                       20075                  10460  ...   

 ПОКАЗАТЕЛИ  Отопление, за Гкал Газ сетевой, за месяц с человека  \
1991                          …                             0.51   
1992                          …                              3.4   
1993                          …                               29   
1994                          …                            64.66   
1995                          …                              951   

 ПОКАЗАТЕЛИ  Электроэнергия в квартирах  без электроплит за минимальный объем потребления29), за 100 кВт·ч  \
1991                                                       3.92                                              
1992                                                       35.1                                              
1993                                                        595                                              
1994                                                    2682.71                                              
1995                                                       8077                                              

 ПОКАЗАТЕЛИ  Кинотеатры, за билет Театры, за билет  \
1991                         1.89             2.87   
1992                        23.82            18.92   
1993                          498              498   
1994                      1972.56          3186.69   
1995                         3886             6185   

 ПОКАЗАТЕЛИ  Посещение детского

In [18]:
raw_df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 1991 to 2021
Data columns (total 85 columns):
 #   Column                                                                                            Non-Null Count  Dtype 
---  ------                                                                                            --------------  ----- 
 0   Говядина (кроме бескостного мяса)                                                                 31 non-null     object
 1   Свинина (кроме бескостного мяса)                                                                  31 non-null     object
 2   Куры охлажденные и мороженые1)                                                                    31 non-null     object
 3   Колбаса вареная2)                                                                                 31 non-null     object
 4   Консервы мясные3), 350 г                                                                          31 non-null     object
 5   Рыба морож

In [19]:
raw_df_2.columns

Index(['Говядина (кроме бескостного мяса)', 'Свинина (кроме бескостного мяса)',
       'Куры охлажденные и мороженые1)', 'Колбаса вареная2)',
       'Консервы мясные3), 350 г', 'Рыба мороженая неразделанная4)',
       'Рыба соленая, маринованная, копченая ',
       'Консервы рыбные натуральные и с добавлением масла,  350 г',
       'Масло сливочное 5) ', 'Масло подсолнечное 6) ',
       'Молоко питьевое цельное  пастеризованное 2,5-3,2% жирности7), за л',
       'Сыры сычужные твердые и мягкие', 'Яйца куриные, за 10 шт.',
       'Сахар-песок', 'Чай черный байховый', 'Мука пшеничная',
       'Хлеб и булочные изделия из пшеничной муки высшего сорта',
       'Рис шлифованный',
       'Макаронные изделия из пшеничной муки высшего сорта8)', 'Картофель',
       'Капуста белокочанная свежая', 'Лук репчатый', 'Яблоки',
       'Водка крепостью 40% об.спирта и выше9), за л',
       'Коньяк ординарный отечественный10), за  л',
       'Вино игристое отечественное11), за  л', 'Пиво отечественное, з

In [20]:
raw_df_2['Отопление, за Гкал'].unique()

array(['…', 1398.66, 1490.71, 1649.18, 1735.87, 1771.19, 1818.6, 1895.33,
       1930.54, 2083.48], dtype=object)

In [22]:
# замена '…' на 0.0
raw_df_3 = raw_df_2.replace('…', 0.0)
raw_df_3['Отопление, за Гкал'].unique()

array([   0.  , 1398.66, 1490.71, 1649.18, 1735.87, 1771.19, 1818.6 ,
       1895.33, 1930.54, 2083.48])

In [23]:
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 1991 to 2021
Data columns (total 85 columns):
 #   Column                                                                                            Non-Null Count  Dtype  
---  ------                                                                                            --------------  -----  
 0   Говядина (кроме бескостного мяса)                                                                 31 non-null     float64
 1   Свинина (кроме бескостного мяса)                                                                  31 non-null     float64
 2   Куры охлажденные и мороженые1)                                                                    31 non-null     float64
 3   Колбаса вареная2)                                                                                 31 non-null     float64
 4   Консервы мясные3), 350 г                                                                          31 non-null     float64
 5   Рыб

In [25]:
# Выводим  ключи столбцов, у которых  тип данных "object" 
# raw_df_3.select_dtypes(include="object").head()
raw_df_3.select_dtypes(include="object").columns

Index(['Еврошифер15), за 10 м2', 'Линолеум, за м2',
       'Кольцо обручальное золотое16), за грамм',
       'Бензин автомобильный марки А-76 (АИ-80)17), за л',
       'Постановка набоек, за пару',
       'Ремонт телевизоров цветного изображения18)  ',
       'Ремонт холодильников всех марок19)', 'Химчистка мужского костюма20)',
       'Стирка и глажение белья прямого21), за кг',
       'Стрижка модельная в женском зале22)',
       'Стрижка модельная в мужском зале', 'Рытье могилы23)',
       'Изготовление гроба', 'Проезд в городском автобусе, за поездку24)',
       'Проезд в трамвае, за поездку', 'Проезд в троллейбусе, за поездку',
       'Проезд в метро, за поездку',
       'Пересылка простого письма внутри России25), массой до 20 г ',
       'Отправка телеграммы обыкновенной внутренней26), за 15 слов',
       'Абонентская плата за неограниченный объем местных телефонных соединений, за месяц',
       'Плата за жилье в домах государственного и муниципального жилищных фондов27), за м2 

In [26]:
raw_df_3['Еврошифер15), за 10 м2'].unique()

array([0.0, '...', 31986.77, 99732, 118529, 126831, 139.32, 213.93, 269.5,
       335.63, 398.32, 460.27, 508.15, 646.24, 734.86, 913.71, 1142.04,
       1144.83, 1154.66, 1232.19, 1289.04, 1368.75, 1425.95, 1494.21,
       1535.18, 2717.7, 2752.78, 2949.49, 3109.3, 4151.1], dtype=object)

In [27]:
# замена '...' на 0.0
raw_df_3 = raw_df_3.replace('...', 0.0)
raw_df_3['Еврошифер15), за 10 м2'].unique()

array([     0.  ,  31986.77,  99732.  , 118529.  , 126831.  ,    139.32,
          213.93,    269.5 ,    335.63,    398.32,    460.27,    508.15,
          646.24,    734.86,    913.71,   1142.04,   1144.83,   1154.66,
         1232.19,   1289.04,   1368.75,   1425.95,   1494.21,   1535.18,
         2717.7 ,   2752.78,   2949.49,   3109.3 ,   4151.1 ])

In [28]:
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 1991 to 2021
Data columns (total 85 columns):
 #   Column                                                                                            Non-Null Count  Dtype  
---  ------                                                                                            --------------  -----  
 0   Говядина (кроме бескостного мяса)                                                                 31 non-null     float64
 1   Свинина (кроме бескостного мяса)                                                                  31 non-null     float64
 2   Куры охлажденные и мороженые1)                                                                    31 non-null     float64
 3   Колбаса вареная2)                                                                                 31 non-null     float64
 4   Консервы мясные3), 350 г                                                                          31 non-null     float64
 5   Рыб

In [29]:
raw_df_3.select_dtypes(include="object").columns

Index(['Бензин автомобильный марки А-76 (АИ-80)17), за л',
       'Постановка набоек, за пару',
       'Ремонт телевизоров цветного изображения18)  ',
       'Ремонт холодильников всех марок19)', 'Химчистка мужского костюма20)',
       'Стирка и глажение белья прямого21), за кг',
       'Стрижка модельная в женском зале22)',
       'Стрижка модельная в мужском зале', 'Рытье могилы23)',
       'Изготовление гроба', 'Проезд в городском автобусе, за поездку24)',
       'Проезд в трамвае, за поездку', 'Проезд в троллейбусе, за поездку',
       'Проезд в метро, за поездку',
       'Пересылка простого письма внутри России25), массой до 20 г ',
       'Отправка телеграммы обыкновенной внутренней26), за 15 слов',
       'Абонентская плата за неограниченный объем местных телефонных соединений, за месяц',
       'Плата за жилье в домах государственного и муниципального жилищных фондов27), за м2 общей площади',
       'Водоснабжение холодное и водоотведение, за месяц с человека',
       'Горячее 

In [30]:
raw_df_3['Бензин автомобильный марки А-76 (АИ-80)17), за л'].unique()

array([0.51, 27.8, 175.59, 595.76, 1681, 1805, 1827, 1.96, 5.75, 7.35,
       6.52, 7.58, 9.06, 12.46, 14.32, 15.75, 17.01, 17.41, 19.16, 20.09,
       24.65, 26.56, 27.91, 30.41, 32.23, 33.59, 35.22, '-'], dtype=object)

In [31]:
raw_df_3 = raw_df_3.replace('-', 0.0)
raw_df_3['Бензин автомобильный марки А-76 (АИ-80)17), за л'].unique()

array([5.1000e-01, 2.7800e+01, 1.7559e+02, 5.9576e+02, 1.6810e+03,
       1.8050e+03, 1.8270e+03, 1.9600e+00, 5.7500e+00, 7.3500e+00,
       6.5200e+00, 7.5800e+00, 9.0600e+00, 1.2460e+01, 1.4320e+01,
       1.5750e+01, 1.7010e+01, 1.7410e+01, 1.9160e+01, 2.0090e+01,
       2.4650e+01, 2.6560e+01, 2.7910e+01, 3.0410e+01, 3.2230e+01,
       3.3590e+01, 3.5220e+01, 0.0000e+00])

In [32]:
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 1991 to 2021
Data columns (total 85 columns):
 #   Column                                                                                            Non-Null Count  Dtype  
---  ------                                                                                            --------------  -----  
 0   Говядина (кроме бескостного мяса)                                                                 31 non-null     float64
 1   Свинина (кроме бескостного мяса)                                                                  31 non-null     float64
 2   Куры охлажденные и мороженые1)                                                                    31 non-null     float64
 3   Колбаса вареная2)                                                                                 31 non-null     float64
 4   Консервы мясные3), 350 г                                                                          31 non-null     float64
 5   Рыб

In [33]:
raw_df_3.select_dtypes(include="object").columns

Index(['Постановка набоек, за пару',
       'Ремонт телевизоров цветного изображения18)  ',
       'Ремонт холодильников всех марок19)', 'Химчистка мужского костюма20)',
       'Стирка и глажение белья прямого21), за кг',
       'Стрижка модельная в женском зале22)',
       'Стрижка модельная в мужском зале', 'Рытье могилы23)',
       'Изготовление гроба', 'Проезд в городском автобусе, за поездку24)',
       'Проезд в трамвае, за поездку', 'Проезд в троллейбусе, за поездку',
       'Проезд в метро, за поездку',
       'Пересылка простого письма внутри России25), массой до 20 г ',
       'Отправка телеграммы обыкновенной внутренней26), за 15 слов',
       'Абонентская плата за неограниченный объем местных телефонных соединений, за месяц',
       'Плата за жилье в домах государственного и муниципального жилищных фондов27), за м2 общей площади',
       'Водоснабжение холодное и водоотведение, за месяц с человека',
       'Отопление28), за м2 общей площади', 'Газ сетевой, за месяц с челове

In [34]:
raw_df_3['Постановка набоек, за пару'].unique()

array([4.75, 92.17, 1683, 5498.27, 11532, 15024, 17168, 21.15, 28.7,
       36.42, 45.1, 56.28, 66.96, 79.6, 93.12, 105.53, 121.67, 145.52,
       166.34, '180,16', 212.25, 228.73, 241.94, 260.75, 290.62, 318.79,
       325.66, 330.22, 342.9, 351.59, 390.92], dtype=object)

In [35]:
# Замена "," на "."
raw_df_3 = raw_df_3.replace(',', '.', regex=True)
raw_df_3['Постановка набоек, за пару'].unique()

array([4.75, 92.17, 1683, 5498.27, 11532, 15024, 17168, 21.15, 28.7,
       36.42, 45.1, 56.28, 66.96, 79.6, 93.12, 105.53, 121.67, 145.52,
       166.34, '180.16', 212.25, 228.73, 241.94, 260.75, 290.62, 318.79,
       325.66, 330.22, 342.9, 351.59, 390.92], dtype=object)

In [36]:
# конвертируем весь дата фрейм в значение "float"
raw_df_3 = raw_df_3.astype("float")
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 1991 to 2021
Data columns (total 85 columns):
 #   Column                                                                                            Non-Null Count  Dtype  
---  ------                                                                                            --------------  -----  
 0   Говядина (кроме бескостного мяса)                                                                 31 non-null     float64
 1   Свинина (кроме бескостного мяса)                                                                  31 non-null     float64
 2   Куры охлажденные и мороженые1)                                                                    31 non-null     float64
 3   Колбаса вареная2)                                                                                 31 non-null     float64
 4   Консервы мясные3), 350 г                                                                          31 non-null     float64
 5   Рыб